### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása és exploratory testing

### ISSUE THREAD

**Issue by tuskajozsef** [BME-MIT-IET/Git-egylet2020-iet-2020#2]

**Comment by mars1277** [comment]
Manuális tesztek megtervezése, végrehajtása > 1. teszt eset
https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/a151b8d056c018c162279ff4cd239b077f33971b

**Comment by mars1277** [comment]
Manuális tesztek megtervezése, végrehajtása > 2. teszt eset
https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/5cb4740be9bb178a18dcd2de18f59907e37fcce7

**Comment by mars1277** [comment]
Manuális tesztek megtervezése, végrehajtása > 3. teszt eset
https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/53575f007583d45d743ede809b1016974963862f

**Comment by mars1277** [comment]
Exploratory testing > 1. charter
https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/e70c3f170236b576935744d818112c4b462131aa
https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/f53f1f6223a8ac7e2f256dc0d053189da53ed0ef

**Comment by mars1277** [comment]
Összegzés
https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/e70c3f170236b576935744d818112c4b462131aa

**Comment by mars1277** [comment]
A https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/pull/7 https://github.com/Monopo1i ellenőrizte.
