### ISSUE TITLE
Manuális kód átvizsgálás és statikus analízis

### ISSUE THREAD

**Issue by tuskajozsef** [BME-MIT-IET/Git-egylet2020-iet-2020#4]

**Comment by Monopo1i** [comment]
Statikus analízis integrálás: https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/2ec69c12574c45f8c0cf89c22c35e10f1b2b6482

**Comment by Monopo1i** [comment]
Statikus analízis eszközök által jelzett hibák javítása ezen a branch-en történik: [branch-static-analysis](https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/tree/branch-static-analysis)

**Comment by Monopo1i** [comment]
Statikus analízis eszköz által jelzett magas kognitív komplexitású függvények refaktorálása:
 - https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/1ffffac4e10bf203be72cc5df261fd971fdbfed9
 - https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/b98aab605c8377d5d8ea2ec9a618d6ebcdd11842
 - https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/commit/5459a4b999f58d70bec3c46d0a752bc6b05584a8

**Comment by Monopo1i** [comment]
Statikus analízis dokumentációja: [Statikus analizis.md](https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/blob/master/doc/Statikus%20analizis.md)

**Comment by Monopo1i** [comment]
A [pull requestet](https://github.com/BME-MIT-IET/Git-egylet2020-iet-2020/pull/6) [Kovács Krisztián](https://github.com/mars1277) ellenőrizte.
